source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target "Haidao" do

pod 'AFNetworking', '~> 3.0'
pod 'Masonry', '~> 0.6.4'
pod 'MBProgressHUD', ‘~> 0.9.2’
pod 'MJExtension’, ‘~> 3.0.10’
pod 'MJRefresh’, ‘~> 3.1.0’
pod 'SDWebImage’, ‘~> 3.7.5’
pod 'ReactiveObjC', '~> 2.1.0'
pod 'TSMessages', '~> 0.9.12'

end
